version: 2
updates:
  - package-ecosystem: npm
    directory: /
    target-branch: milestone-3-release-verification
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: github-actions
    directory: /
    target-branch: milestone-3-release-verification
    schedule:
      interval: weekly
